apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: {{ .Release.Namespace }}
  labels: {{- include "quickstart.serviceLabels" (dict "ctx" . "service" "control-plane") | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "quickstart.serviceSelectorLabels" (dict "service" "control-plane") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
